services:
  - type: web
    name: phishing-domain-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MLFLOW_TRACKING_URI
        value: https://mlflow.your-domain.com # You'll need to update this
      - key: MLFLOW_EXPERIMENT_NAME
        value: phishing_detection
      - key: PORT
        value: 8000 