services:
  - type: web
    name: phishing-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: CASSANDRA_HOST
        sync: false
      - key: CASSANDRA_PORT
        sync: false
      - key: MLFLOW_TRACKING_URI
        sync: false
      - key: PORT
        sync: false
    healthCheckPath: /health
    autoDeploy: true 